name: Event System Tests

on:
  push:
    branches: [ main, master, dev, development ]
  pull_request:
    branches: [ main, master, dev, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PySide6 which is required for the UI components
        pip install PySide6>=6.4.0
        # Install other dependencies
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install X Virtual Frame Buffer for QT
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
    - name: Run all tests
      run: |
        xvfb-run python -m unittest test_events.py
        
    - name: Run comprehensive event processing test
      run: |
        xvfb-run python -m unittest test_events.TestEvents.test_all_events_processable
        
    - name: Run schema validation test
      run: |
        xvfb-run python -m unittest test_events.TestEvents.test_event_schema_validation
        
    - name: Run unrealistic events tests
      run: |
        xvfb-run python -m unittest test_events.TestEvents.test_unrealistic_events
        
    - name: Test combined event pool (realistic + unrealistic)
      run: |
        xvfb-run python -m unittest test_events.TestEvents.test_combined_event_pool
        
    # Create empty unrealistic events file if one doesn't exist (for testing purposes)
    - name: Ensure unrealistic events file exists
      run: |
        mkdir -p madden_franchise_qt/data
        if [ ! -f madden_franchise_qt/data/unrealistic_events.json ]; then
          echo '{"unrealistic_events": []}' > madden_franchise_qt/data/unrealistic_events.json
          echo "Created empty unrealistic_events.json file for testing"
        fi 